
SetNodeLabel = true
NodeLabel = "maintenance.box.com/source=npd"
log_file = "/var/log/service/node-alert-generator.log"
namespace = "node-alert-generator"

[healthcheck]
server = "0.0.0.0"
port = 8080

[config_map]
name = "npd-alerts"
#ConfigMap update interval
frequency = "60s"

[node_status]
include_not_ready = true

[label_filter.exclude]
key = "maintenance.box.com/source"
not_val = "npd"
not_match = "node-alert-worker.*"

[label_filter.include]
key = "box.com/pool"
match_val = "calico"

#Settings for recovering cordoned node
[cordoned]
duration = "5h"  #maintenance.box.com/draintime needs to be more than this period
check_frequency = "1h"

[condition.options]
match = "NPD-.*"
#Only consider conditions whose last heartbeat time is within this interval
interval = "25h" # h stands for hours, s stands for seconds

#Node conditions to Actions mapping
[condition.name.npd-kubeletproxycertexpiring]
name = "NPD-KubeletProxyCertExpiring"
action = "plays/auto-remediation/knr_verify_disabled_v1.yml"
success_wait = "2h"
failed_retry = "3"

[condition.name.npd-kubeletisdown]
name = "NPD-KubeletIsDown"
action = "plays/auto-remediation/knr_verify_disabled_v1.yml"
success_wait = "2h"
failed_retry = "3"

[condition.name.npd-calicodown]
name = "NPD-CalicoDown"
action = "plays/auto-remediation/knr_verify_disabled_v1.yml"
success_wait = "2h"
failed_retry = "3"

[condition.name.npd-calicoetcdissue]
name = "NPD-CalicoEtcdIssue"
action = "plays/auto-remediation/knr_drain_bounce_calico.yml"
success_wait = "2h"
failed_retry = "3"

[condition.name.node-cordoned]
name = "Node-Cordoned"
action = "plays/auto-remediation/knr_verify_disabled_v1.yml"
success_wait = "2h"
failed_retry = "3"


