
SetNodeLabel = false
NodeLabel = "maintenance.box.com/source=npd"
#log_file = "/var/log/service/node-alert-generator.log"
log_file = "/tmp/node-alert-generator.log"
namespace = "node-alert-generator"

[healthcheck]
server = "0.0.0.0"
port = 8080

[config_map]
name = "npd-alerts"
#ConfigMap update interval
frequency = "30s"

[node_status]
cordoned_within = "1m"
cordoned_check_frequency = "20s" 
include_not_ready = true

[label_filter.exclude]
key = "maintenance.box.com/source"
not_val = "npd"
not_match = "node-alert-worker-.*"

[condition.options]
match = "NPD-.*"
#Only consider conditions whose last heartbeat time is within this interval
interval = "25h" # h stands for hours, s stands for seconds

#Node conditions to Actions mapping
#[condition.name.npd-puppetrundelayed]
#name = "NPD-PuppetRunDelayed"
#action = "test1.yml"
#success_wait = "1m"
#failed_retry = "2"
#
#[condition.name.npd-chronyissue]
#name = "NPD-ChronyIssue"
#action = "test1.yml"
#success_wait = "1m"
#failed_retry = "2"
#
#[condition.name.node-not-ready]
#name = "Node-Not-Ready"
#action = "test1.yml"
#success_wait = "1m"
#failed_retry = "2"
#
#[condition.name.node-cordoned]
#name = "Node-Cordoned"
#action = "test1.yml"
#success_wait = "1m"
#failed_retry = "2"

